//'use client';

import type { Metadata } from "next";
import "./styles.css";

export const metadata: Metadata = {
  title: "TMDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        {children}
      </body>
    </html>
  );
}
